require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config/initializers/**'
    - 'config/environments/**'
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false